# Generated by Django 3.0.7 on 2020-06-16 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundstrackerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialgoal',
            name='is_completed',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
