# Generated by Django 3.0.7 on 2020-06-19 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fundstrackerapp', '0004_journalentry_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='financial_goal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fundstrackerapp.FinancialGoal'),
            preserve_default=False,
        ),
    ]
