# Generated by Django 3.0.7 on 2020-06-19 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fundstrackerapp', '0005_journalentry_financial_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='financial_goal',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='fundstrackerapp.FinancialGoal'),
        ),
    ]
