# Generated by Django 3.0.5 on 2020-06-25 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fundstrackerapp', '0009_auto_20200624_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='financial_goal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='fundstrackerapp.FinancialGoal'),
        ),
    ]
